# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
env:
  matrix:
    - TEST_SDK=iphonesimulator7.1
    - TEST_SDK=iphonesimulator8.1
script:
- pod lib lint && xctool build-tests && xctool run-tests -test-sdk $TEST_SDK
