# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
env:
  matrix:
    - TEST_SDK=iphonesimulator7.0
    - TEST_SDK=iphonesimulator7.1
    - TEST_SDK=iphonesimulator8.0
    - TEST_SDK=iphonesimulator8.1
script:
- xctool build-tests && xctool test -test-sdk $TEST_SDK
